# Generated by Django 5.2.6 on 2025-11-18 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=200)),
                ("section_order", models.IntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                ("min_words", models.IntegerField(default=0)),
                ("max_words", models.IntegerField(default=0)),
                ("description", models.TextField()),
                (
                    "prompt_template",
                    models.TextField(help_text="Template for AI generation"),
                ),
                ("example_content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Proposal Template",
                "verbose_name_plural": "Proposal Templates",
                "db_table": "proposal_templates",
                "ordering": ["proposal_type", "section_order"],
            },
        ),
        migrations.CreateModel(
            name="ProposalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("horizon_europe", "Horizon Europe"),
                            ("europol", "Europol"),
                            ("nsf", "National Science Foundation (NSF)"),
                            ("nih", "National Institutes of Health (NIH)"),
                            ("erc", "European Research Council (ERC)"),
                            ("marie_curie", "Marie Skłodowska-Curie Actions"),
                            ("wellcome_trust", "Wellcome Trust"),
                            ("gates_foundation", "Gates Foundation"),
                            ("darpa", "DARPA"),
                            ("uk_research", "UK Research and Innovation"),
                            ("custom", "Custom Template"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="proposal_types/"
                    ),
                ),
                ("min_pages", models.IntegerField(default=10)),
                ("max_pages", models.IntegerField(default=100)),
                ("required_sections", models.JSONField(default=list)),
                ("optional_sections", models.JSONField(default=list)),
                ("guidelines_url", models.URLField(blank=True, null=True)),
                ("submission_deadline", models.DateField(blank=True, null=True)),
                ("template_style", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Proposal Type",
                "verbose_name_plural": "Proposal Types",
                "db_table": "proposal_types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="savedproposal",
            name="citations_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="savedproposal",
            name="content_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="savedproposal",
            name="is_latest",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="savedproposal",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="savedproposal",
            name="page_count",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="savedproposal",
            name="parent_proposal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="authentication.savedproposal",
            ),
        ),
        migrations.AddField(
            model_name="savedproposal",
            name="retrieved_papers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="savedproposal",
            name="share_token",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="savedproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In Progress"),
                    ("review", "Under Review"),
                    ("final", "Final"),
                    ("submitted", "Submitted"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="savedproposal",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedproposal",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="savedproposal",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="orcid",
            field=models.CharField(
                blank=True, help_text="ORCID iD", max_length=19, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_proposals_generated",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_proposals_saved",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_words_generated",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ProposalAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("generate", "Generate Proposal"),
                            ("enhance", "Enhance Proposal"),
                            ("save", "Save Proposal"),
                            ("download", "Download Proposal"),
                            ("delete", "Delete Proposal"),
                            ("share", "Share Proposal"),
                            ("view", "View Proposal"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="authentication.savedproposal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "proposal_analytics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProposalCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("editor", "Editor"),
                            ("reviewer", "Reviewer"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborators",
                        to="authentication.savedproposal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal Collaborator",
                "verbose_name_plural": "Proposal Collaborators",
                "db_table": "proposal_collaborators",
            },
        ),
        migrations.CreateModel(
            name="ProposalSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=200)),
                ("section_order", models.IntegerField(default=0)),
                ("content", models.TextField()),
                ("word_count", models.IntegerField(default=0)),
                ("citation_count", models.IntegerField(default=0)),
                ("is_complete", models.BooleanField(default=False)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="authentication.savedproposal",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.proposaltemplate",
                    ),
                ),
            ],
            options={
                "db_table": "proposal_sections",
                "ordering": ["proposal", "section_order"],
            },
        ),
        migrations.CreateModel(
            name="ProposalComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="authentication.savedproposal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="authentication.proposalsection",
                    ),
                ),
            ],
            options={
                "db_table": "proposal_comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="proposaltemplate",
            name="proposal_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="authentication.proposaltype",
            ),
        ),
        migrations.AddField(
            model_name="savedproposal",
            name="proposal_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.proposaltype",
            ),
        ),
        migrations.AddIndex(
            model_name="savedproposal",
            index=models.Index(
                fields=["user", "-created_at"], name="saved_propo_user_id_782b57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedproposal",
            index=models.Index(fields=["status"], name="saved_propo_status_2d1533_idx"),
        ),
        migrations.AddIndex(
            model_name="savedproposal",
            index=models.Index(
                fields=["proposal_type"], name="saved_propo_proposa_d7c9d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proposalanalytics",
            index=models.Index(
                fields=["user", "-created_at"], name="proposal_an_user_id_a32a72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proposalanalytics",
            index=models.Index(fields=["action"], name="proposal_an_action_08accc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="proposalcollaborator",
            unique_together={("proposal", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="proposalsection",
            unique_together={("proposal", "section_name")},
        ),
        migrations.AlterUniqueTogether(
            name="proposaltemplate",
            unique_together={("proposal_type", "section_name")},
        ),
    ]
